---
root: true
env:
  es2020: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules: {
  "@typescript-eslint/no-explicit-any": "off"
}
overrides:
  - files:
      - '*.tsx'
      - '*.ts'
      - '*.jsx'
      - '*.js'
    processor: '@graphql-eslint/graphql'
  - files:
      - '*.graphql'
    parser: '@graphql-eslint/eslint-plugin'
    plugins:
      - '@graphql-eslint'
    rules: {}
